spring:
  application:
    name: eurekaserver
server:
  port: 9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    fetch-registry: false
    register-with-eureka: false
